# Generated by Django 4.1.3 on 2022-11-20 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст сообщения')),
                ('date_start', models.DateTimeField(verbose_name='время запуска')),
                ('date_finish', models.DateTimeField(verbose_name='время окончания')),
            ],
        ),
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Код мобильного оператора')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.DecimalField(decimal_places=0, max_digits=10, unique=True, verbose_name='Номер телефона без +7')),
                ('customer_tz', models.CharField(blank=True, max_length=100, verbose_name='Часовой пояс')),
                ('carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.carrier', verbose_name='Код мобильного оператора')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=20, verbose_name='Тег')),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=200, unique=True, verbose_name='фильтр по:')),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.carrier', verbose_name='Фильтр по оператору')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tag', verbose_name='Фильтр по тегу')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_time', models.DateTimeField(auto_now_add=True, verbose_name='Время отправки')),
                ('is_ok', models.BooleanField(default=False, verbose_name='Статус отправки')),
                ('campaign_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email', to='core.campaign', verbose_name='ID рассылки')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='email', to='core.customer', verbose_name='ID клиента')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tag', verbose_name='Тег'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='email_filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.filter', verbose_name='фильтр для рассылки'),
        ),
    ]
