# Generated by Django 4.1.3 on 2022-11-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.DecimalField(decimal_places=0, max_digits=10, unique=True, verbose_name='Номер телефона без +7'),
        ),
    ]
