# Generated by Django 4.1.3 on 2022-11-16 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customer_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='is_sent',
            new_name='is_ok',
        ),
    ]
