# Generated by Django 4.1.3 on 2022-11-19 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_filter_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='tag',
            field=models.ForeignKey(blank=True, default='Yandex', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tag', verbose_name='Фильтр по тегу'),
        ),
    ]
